services:

  web:
    build: .
    ports:
      - "${EXPENSES_PORT}:8000"
    volumes:
      - "./logs:/home/nonroot/app/logs"
      - "./app/static:/home/nonroot/app/app/static"
      - "./app/templates:/home/nonroot/app/app/templates"
      - "./tests:/home/nonroot/app/tests"
      - "./db:/home/nonroot/app/db"
    environment:
      EXPENSES_USERNAME: "${EXPENSES_USERNAME}"
      EXPENSES_PASSWORD: "${EXPENSES_PASSWORD}"
#    healthcheck:
#      test: "wget --no-verbose --tries=1 --spider http://${DOMAIN}/nsfootball/ping/ || exit 1"
#      interval: "1m"
#      timeout: "5s"
#      retries: 3
#      start_period: "30s"
    restart: "always"
    networks:
      expenses-net:

networks:
  expenses-net:
