.pytest_cache/
__pycache__/
.venv/
.env
.idea/
.git/
.gitignore

*.dockerignore
Dockerfile.*
Dockerfile

pytest.ini
tests/
templates/
static/
logs/
db/

*.yml
README.md
LICENSE
ruff.toml
pdm.lock
.pdm-python
.pre-commit-config.yaml
